// Generated by scripts/generate-build-metadata.sh from Config/Version.env.
import Foundation
public enum BuildMetadata {
    public static let version = "0.5.0"
    public static let build = "1"
    public static let helperProtocolVersion = 1
    public static let macVDMToolRevision = "b22ae51eb43a0e1daa21d41616ac899f28e7bf8a"
    public static var gitCommit: String { Bundle.main.object(forInfoDictionaryKey: "DFUUtilityGitCommit") as? String ?? "Development" }
    public static var buildDate: String { Bundle.main.object(forInfoDictionaryKey: "DFUUtilityBuildDate") as? String ?? "Development" }
    public static var displayVersion: String { "\(version) (\(build))" }
}
