#!/bin/sh
set -eu
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
. "$root/Config/Version.env"
output="$root/Sources/DFUCore/BuildMetadata.generated.swift"
temporary=$(mktemp "${TMPDIR:-/tmp}/dfu-build-metadata.XXXXXX")
trap 'rm -f "$temporary"' EXIT
{
  echo '// Generated by scripts/generate-build-metadata.sh from Config/Version.env.'
  echo 'import Foundation'
  echo 'public enum BuildMetadata {'
  printf '    public static let version = "%s"\n' "$MARKETING_VERSION"
  printf '    public static let build = "%s"\n' "$BUILD_NUMBER"
  printf '    public static let helperProtocolVersion = %s\n' "$HELPER_PROTOCOL_VERSION"
  printf '    public static let macVDMToolRevision = "%s"\n' "$MACVDMTOOL_REVISION"
  echo '    public static var gitCommit: String { Bundle.main.object(forInfoDictionaryKey: "DFUUtilityGitCommit") as? String ?? "Development" }'
  echo '    public static var buildDate: String { Bundle.main.object(forInfoDictionaryKey: "DFUUtilityBuildDate") as? String ?? "Development" }'
  echo '    public static var displayVersion: String { "\(version) (\(build))" }'
  echo '}'
} > "$temporary"
if ! cmp -s "$temporary" "$output" 2>/dev/null; then mv "$temporary" "$output"; fi
